### ISSUE TITLE
OhNo images on drills

### ISSUE THREAD

**Issue by SakuraLilly** [LokeYourLord/Extremely-Efficient-Structures#1]
For the life of me I do not understand why. 
But the drills give OhNo images.

**Comment by LokeYourC3PH** [comment]
Well, two things.
1: Thank you for actually bothering to open an issue tracker.
2: I am really sorry about that. I think that I _**might**_ have time to fix it today, but I can't promise it 100%.

**Comment by LokeYourC3PH** [comment]
Fixed in [release 1.6](https://github.com/LokeYourLord/Extremely-Efficient-Structures/releases/tag/1.6)

**Comment by SakuraLilly** [comment]
I have 3 mods of my own. I was hoping I could help you after I read your steam comment. Maybe even fix it for you. But my mods are Hjson, so not sure if it is in the file. Because the images are normal and have the right names.

**Comment by LokeYourC3PH** [comment]
> 
> 
> I have 3 mods of my own. I was hoping I could help you after I read your steam comment. Maybe even fix it for you. But my mods are Hjson, so not sure if it is in the file. Because the images are normal and have the right names.

Yeah don't worry about it I already managed to fix it, but thanks a lot 😊
